### ISSUE TITLE
[1.20.6] Exception in server tick loop

### ISSUE THREAD

**Issue by Kardane** [snackbag/TT20#4]
Crash at 1.20.6 fabric server start up

Crash Report:
========================
java.lang.RuntimeException: Mixin transformation of net.minecraft.server.dedicated.DedicatedServerWatchdog failed
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base@22.0.1/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at MC//net.minecraft.server.dedicated.MinecraftDedicatedServer.setupServer(MinecraftDedicatedServer.java:200)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:658)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275)
	at java.base@22.0.1/java.lang.Thread.run(Thread.java:1570)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at app//org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at app//org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at app//org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 8 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method cancelServerWatchdog(J)J in tt20.mixins.json:DedicatedServerWatchdogMixin from mod tt20 failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap tt20-0.5.0+mc1.20.1-refmap.json
	at app//org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at app//org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at app//org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at app//org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at app//org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at app//org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at app//org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at app//org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 11 more
	
==========================	
	
Used Mods:
alternate-current: Alternate Current 1.8.0-beta.4
		better-fabric-console: Better Fabric Console 1.1.9
		carpet: Carpet Mod 1.4.141+v240429
		cloth-config: Cloth Config v14 14.0.126
		eyespy: Eye Spy 1.3.7+1.20.5
		fabpose: FabPose 1.0.0+1.20.6
		fabric-api: Fabric API 0.99.0+1.20.6
		fabric-language-kotlin: Fabric Language Kotlin 1.10.20+kotlin.1.9.24
		fabricloader: Fabric Loader 0.15.11
		farmtweaks: FarmTweaks 1.1+1.20.6
		ferritecore: FerriteCore 6.1.1
		fullstackwatchdog: FullStack Watchdog 1.0.1+1.19.2-fabric
		invview: InvView 1.4.15-1.20.5+
		java: Java HotSpot(TM) 64-Bit Server VM 22
		karns_usefulcommand: karnsusefulcommand 2.0
		koreanchat: koreanChat 1.4
		krypton: Krypton 0.2.7
		lithium: Lithium 0.12.3
		luckperms: LuckPerms 5.4.125
		midnightlib: MidnightLib 1.5.5
		minecraft: Minecraft 1.20.6
		modernfix: ModernFix 5.17.3+mc1.20.6
		nochatreports: No Chat Reports 1.20.6-v2.7.0
		noisium: Noisium 2.1.0+mc1.20.5-1.20.6
		notica: Notica 1.1.3+1.20.6
		polymer-bundled: Polymer 0.8.4+1.20.6
		potatoptimize: potatoptimize 0.0.1
		recipecooldown: Recipe Cooldown 1.17.1-1.0.0
		score-migrator: Score Migrator 1.20.3-1.0.2
		semblance: Semblance 1.1.5
		spark: spark 1.10.65
		stackdeobfuscator: StackDeobfuscator 1.4.3+08e71cc
		styledchat: Styled Chat 2.5.0+1.20.5
		styledplayerlist: Styled Player List 3.4.0+1.20.5
		suggestion_tweaker: Suggestion Tweaker 1.20.6-1.5.2
		threadtweak: ThreadTweak 1.20.6-0.1.3
		tt20: TT20 0.5.0
		worldedit: WorldEdit 7.3.2+6779-3aca580

**Comment by JXSnack** [comment]
Heyho! This should be fixed in the update I'm about to release. I'll notify you again when it's released :]

**Comment by JXSnack** [comment]
I've just released a potential fix on [Modrinth](https://modrinth.com/mod/tt20) and [GitHub](https://github.com/snackbag/TT20/releases/tag/v0.5.1-beta) - Please tell me if this fixed it

**Comment by guicale** [comment]
I'm getting the same exception on 1.20.4, using version 5.1 of the mod:
```
java.lang.RuntimeException: Mixin transformation of net.minecraft.server.dedicated.DedicatedServerWatchdog failed
        at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
        at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
        at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
        at app//net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
        at java.base@17.0.11/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at MC//net.minecraft.server.dedicated.MinecraftDedicatedServer.setupServer(MinecraftDedicatedServer.java:189)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:650)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
        at java.base@17.0.11/java.lang.Thread.run(Thread.java:840)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at app//org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
        at app//org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
        at app//org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
        at app//net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
        ... 8 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method cancelServerWatchdog(J)J in tt20.mixins.json:DedicatedServerWatchdogMixin from mod tt20 fa  led injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap tt20-0.5.1+mc1.20.1-refmap.json
        at app//org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
        at app//org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
        at app//org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
        at app//org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
        at app//org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
        at app//org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
        at app//org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
        at app//org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        ... 11 more
```

My mod list is:
- advancedbackups 3.6
- afkplus 1.4.9                                                 
- alivent-messenger 1.3.2
- alternate-current 1.8.0-beta.4
- architectury 11.1.17
- asynclocator 1.3.0
- balm-fabric 9.0.9
- better_log4j_config 1.2.0
- bettersafebed 1.20.4-14
- betterstats 3.9.7+fabric-1.20.4                                                        
- bundle_recipe v1.0.1
- c2me 0.2.0+alpha.11.67                                                              
- calmdowndog 1.1.0
- cartloader 1.0-SNAPSHOT
- chunky 1.3.146
- cloth-config 13.0.121                                                               
- connected-doors 1.2+1.20
- crops_love_rain 1.5.0+1.20.4
- deepslatecutting 1.7.0
- discerning_furnace 1.0.15
- elytratrims 3.4.0                                                                 
- fabric-api 0.97.1+1.20.4
- fabric-permissions-api-v0 0.3.1
- fabricloader 0.15.11                                                                       
- fabrictailor 2.3.1                                                                   
- fallingtree 1.20.4.3
- ferritecore 6.0.3
- fix-mc-stats 1.0.0
- invview 1.4.14-1.20.4+                                                                       
- jade 13.3.1
- java 17                                                                                          
- krypton 0.2.6                               
- ksyxis 1.3.2
- leashmod 1.0.6
- leaves_us_in_peace 1.0.22                                                         
- letmedespawn 1.2.1
- letsjeb 3.0.0
- linkart 5.4.4-1.20.2-build.133
- lithium 0.12.1
- memoryleakfix 1.1.5
- midnightlib 1.5.3
- minecraft 1.20.4
- mixintrace 1.1.1+1.17
- mr_banner_bedsheets 1.2
- mr_banner_flags 2.3
- mr_stonecutter_damage 1-mcmeta-12-41_1.19.4-1.20.5
- nethermap 4.0.0-1.20.2
- netherportalfix 15.0.1
- noisium 2.0.3+mc1.20.2-1.20.4
- oth3r-sit 1.1.6+1.20.4
- owo 0.12.6+1.20.3
- pl3xmap 1.20.4-492
- placeholder-api 2.4.0-pre.1+1.20.4
- playerstatistics 0.1.2+1.20.3
- potatoptimize 0.0.1
- reputation 0.2.5+jade.1.20
- safe-respawn 1.0.2
- sensible-sleepiness 0.0.3-1.20+
- servercore 1.5.0+1.20.4
- slumber 1.2.0
- sneakyserver 1.0.12+SNAPSHOT
- snowballkb 1.3-1.20
- spark 1.10.58
- spectatorplus 1.1.0+mc1.20.4
- sqlite-jdbc 3.41.2.1+20230506
- stackables 2.0.1
- stackdeobfuscator 1.4.3+08e71cc                                             
- styledplayerlist 3.3.0+1.20.3                                                            
- suggestion_tweaker 1.20-1.5.2
- tbim 1.0.1
- through-the-lilypads-gently 1.1.1
- timestacker 1.1.3
- tt20 0.5.1
- villagerleads 0.0.2
- villagernames 4.5.4                                                           
- yet_another_config_lib_v3 3.5.0+1.20.4-fabric

**Comment by JXSnack** [comment]
Could you provide the whole mod zip (if it's possible, otherwise i'll attempt to recreate it myself)

**Comment by guicale** [comment]
I've found that the exception still happens without any other mods enabled (only Fabric API and TT20 5.1), running 1.20.4 with Fabric Loader 0.5.11 on Debian Stable with OpenJDK 17. I can still provide all the mod files, though I don't see much use in that.

**Comment by JXSnack** [comment]
Update: This happens on all versions above 1.20.2

**Comment by JXSnack** [comment]
I've made a hotfix which disables the server watchdog
[1.20.1-1.20.4](https://snackbag.net/extras/imgd/tempjar/tt20-0.5.1-hotfix+mc1.20.1.jar)
[1.20.5-1.20.6](https://snackbag.net/extras/imgd/tempjar/tt20-0.5.1-hotfix+mc1.20.5.jar)
[1.21](https://snackbag.net/extras/imgd/tempjar/tt20-0.5.1-hotfix+mc1.21.jar)

**Comment by JXSnack** [comment]
I found the solution! The issue was that the refmap was for 1.20.1, but the obfuscated method/class/field mappings were incorrect. This should be fixed in the 0.6.0 release!

**Comment by Legendmanj** [comment]
> I found the solution! The issue was that the refmap was for 1.20.1, but the obfuscated method/class/field mappings were incorrect. This should be fixed in the 0.6.0 release!

please mind giving me the 0.6. 0 version when it is released ;)

**Comment by JXSnack** [comment]
Just released v0.6, check it out on [Modrinth](https://modrinth.com/mod/tt20) -- If this issue persists, please reopen it or make a new one.
